# netlify.toml file located in D:\my-ts-app\glowtype-ratata\netlify.toml

[build]
  # CHANGE THIS LINE: Set base to your project folder relative to the Git repo's root
  base = "glowtype-ratata/" 

  # The command to run your build
  command = "npm run build"

  # The directory where the final built files are located, relative to the 'base' directory.
  publish = "dist/" 

  # If you're using Netlify Functions, specify their directory relative to 'base'
  functions = "netlify/functions/" 

# Environment variables for the build process
[build.environment]
  NODE_VERSION = "22.16.0"
