# netlify.toml file located in D:\my-ts-app\glowtype-ratata\netlify.toml

[build]
  # CHANGE THIS LINE from 'base = "."' to:
  base = "glowtype-ratata/" # <--- THIS IS THE CRITICAL CHANGE

  # The rest of your file should look like this:
  command = "npm run build"
  publish = "dist/"
  functions = "netlify/functions/" 

[build.environment]
  NODE_VERSION = "22.16.0"
